{{- $autoscaling := .Values.autoscaling | default (dict) -}}
{{- $installMode := .Values.installMode | default (dict) -}}
{{- if and ($autoscaling.enabled) (not $installMode.crdsRbacOnly) }}
{{/* HPA intentionally omitted; set autoscaling.enabled=false or provide template */}}
{{- end }}
