{{- if and .Values.podDisruptionBudget.enabled (not .Values.installMode.crdsRbacOnly) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "crypto-edge-operator.fullname" . }}
  namespace: {{ include "crypto-edge-operator.namespace" . }}
  labels:
    {{- include "crypto-edge-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
       {{- include "crypto-edge-operator.selectorLabels" . | nindent 6 }}
  {{- if not (or (hasKey .Values.podDisruptionBudget "minAvailable") (hasKey .Values.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: 1 # Default value because minAvailable and maxUnavailable are not set
  {{- end }}
  {{- if hasKey .Values.podDisruptionBudget "minAvailable" }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.podDisruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
