apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-operator-role
rules:
  - apiGroups: ["mesh.openkcm.io"]
    resources: ["tenants"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["mesh.openkcm.io"]
    resources: ["tenants/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update", "get", "list", "watch"]
