apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crypto-edge-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crypto-edge-operator-role
subjects:
  - kind: ServiceAccount
    name: crypto-edge-operator
    namespace: crypto-edge-operator
