apiVersion: v1
kind: Secret
metadata:
  name: acme-remote-kubeconfig
  namespace: krypton-operator
type: Opaque
data:
  kubeconfig: "REPLACEME_BASE64_KUBECONFIG" # base64 encode of remote kubeconfig file
